import type { Metadata } from "next";
import { Noto_Serif } from "next/font/google";
import "./globals.css";

const NotoSerif = Noto_Serif({
  subsets: ["latin"],
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${NotoSerif.variable} antialiased`}>{children}</body>
    </html>
  );
}
